### ISSUE TITLE
Add transaction fee for STAS-20 stablecoin

### ISSUE THREAD

**Issue by Neggia** [stas-token/stas-sdk#4]
It would be really helpful to add a transaction fee that can be defined in contract, maybe as a percentage on output value, for each STAS transaction, paid to the issuer (as STAS tokens or native BSVs), so it can be an economic model to generate income for stablecoins issuers in general

**Comment by cainnusti** [comment]
Thanks for your recommendation. We have considered a new STAS template that will contain a Royalty payment condition where an additional output to a specified address with an amount that has been defined by the user is enforced by the script itself.

As for adding this feature to the STAS-20 token is not possible without creating a new token template type as it would change the make up of the smart contract and is what defines the templates themselves. But some properties of the STAS-20 token may be inherited into this new template. 

So far the finer details of this new template type have not been completed but is definitely in the pipeline for future releases.

Thank you
