### ISSUE TITLE
Add choice for Redeem/RedeemAny  for STAS-20 tokens

### ISSUE THREAD

**Issue by Neggia** [stas-token/stas-sdk#5]
It would be nice to define in contract if redeem for STAS-20 tokens can be standard or RedeemAny

**Comment by cainnusti** [comment]
Thank you for your feedback! Currently the STAS templates all have a specific set or properties that make them unique. This is defined in the smart contract part of the script itself, therefore any changes to the STAS templates would then create a new token type. 

The legacy "STAS" tokens however do have the ability for anyone to redeem them if they are the token owner of the address. The only other difference between the STAS and STAS-20 token is the additional Op Return output that can be added to the STAS-20 transactions that can contain additional meta data etc.
