### ISSUE TITLE
Cannot read properties of undefined (reading 'BN')

### ISSUE THREAD

**Issue by Neggia** [stas-token/stas-sdk#6]
Debugging locally stas-sdk and on const stas = require('stas-sdk') I get errorMessage "Cannot read properties of undefined (reading 'BN')". Seems that error line is const BN = bsv.crypto.BN.
I think a similar error was found and fixed on TAAL web wallet by Arnaldas who said to me:
"bsv library uses a wrapper for bn.js (https://github.com/moneybutton/bsv/blob/master/lib/bn.js) and they have implemented few additional methods here, as the lib is a little bit messy, we have a mix of multiple versions here"
"if you see somewhere in stas-js calling BN.fromNumber then it's not right, we should import BN from 'bn.js and do const n = new BN(x) (https://github.com/TAAL-GmbH/taal-wallet/commit/2da65dd1d30c0ef913ce771cbe654c1b8b9144c1#diff-b44070b08856e39ca62dfc4309210ccb9c43bf9b8494c4219786cc8578421b1dL435)".
Please fix ASAP so I can continue developing on stas-sdk,
best regards.

**Comment by cainnusti** [comment]
Apologies for the late response! The issue was not showing from my side on the unit tests, but have made the recommended changes that will be added later today. Please let me know if this is resolved on your end once the code is merged. Thank you for your patience.
